### ISSUE TITLE
Account name location changes when opening the options dialog

### ISSUE THREAD

**Issue by PhiliPdB** [woording/woording-web#16]
Like here:
![2016-01-19](https://cloud.githubusercontent.com/assets/7051056/12429414/66e870d2-beea-11e5-808e-193925ebdb65.png)

**Comment by LeonGr** [comment]
Could not reproduce error on Chrome or Midori (eOS browser). What browser are you using? Firefox?

**Comment by PhiliPdB** [comment]
Yes, Firefox 44.0
