### ISSUE TITLE
friend request email points to localhost 

### ISSUE THREAD

**Issue by cor** [woording/woording-web#36]
![image](https://cloud.githubusercontent.com/assets/4728062/13709576/f4d0fae8-e7b4-11e5-9e22-2cf072cdde9c.png)

**Comment by PhiliPdB** [comment]
Is the friend request sent from your local server?

**Comment by cor** [comment]
Nope, it's sent directly from woording.com

**Comment by PhiliPdB** [comment]
Okey important to know. I think that this is a bug in the API by the way.

**Comment by cor** [comment]
Indeed, I should've posted this issue in woording/woording-api

**Comment by PhiliPdB** [comment]
Okey moved it
